version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: socialhub-postgres
    environment:
      POSTGRES_DB: socialhub_pro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - socialhub-network

  # Redis 缓存和队列
  redis:
    image: redis:7-alpine
    container_name: socialhub-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - socialhub-network

  # SocialHub Pro 应用
  app:
    build: .
    container_name: socialhub-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/socialhub_pro
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_SECRET=your-super-secret-jwt-key-here
      - NEXTAUTH_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - socialhub-network
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

volumes:
  postgres_data:
  redis_data:

networks:
  socialhub-network:
    driver: bridge